# 1. Creiamo l'identità specifica per Jenkins
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-admin
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: jenkins
---
# 2. Definiamo i poteri (Role)
# Usiamo un Role (namespace-scoped) per la massima sicurezza
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-admin-role
  namespace: {{ .Release.Namespace | quote }}
rules:
- apiGroups: ["kafka.strimzi.io"]
  resources: ["kafkatopics", "kafkausers", "kafkaconnectors", "kafkarebalances", "kafkas"]
  verbs: ["*"] 
- apiGroups: [""]
  # Aggiunti 'pods' e 'pods/log' necessari per far girare gli agenti Kubernetes
  resources: ["secrets", "configmaps", "pods", "pods/exec", "pods/log", "services"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch"]
---
# 3. Colleghiamo l'identità ai poteri (RoleBinding)
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-admin-binding
  namespace: {{ .Release.Namespace | quote }}
subjects:
- kind: ServiceAccount
  name: jenkins-admin
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: Role
  name: jenkins-admin-role
  apiGroup: rbac.authorization.k8s.io