---
# Kubernetes
k8s_namespace: kafka-lab

# Strimzi Kafka Cluster (KRaft mode)
kafka_cluster_name: kafka-cluster
kafka_nodepool_name: kafka
kafka_bootstrap_servers: "kafka-cluster-kafka-bootstrap:9092"
kafka_bootstrap_servers_tls: "kafka-cluster-kafka-bootstrap:9093"

# Admin credentials
kafka_admin_user: admin
kafka_admin_password: admin-secret

# URLs (NodePort)
kafka_ui_url: "http://localhost:30080"
prometheus_url: "http://localhost:30090"
grafana_url: "http://localhost:30030"
grafana_admin_user: admin
grafana_admin_password: admin
